// ── Sample Data for Hunchmate MVP ──

export const sampleEvents = [
  {
    id: 'evt-001',
    title: 'Neural Nexus Hackathon 2026',
    category: 'Hackathon',
    mode: 'Hybrid',
    status: 'open',
    description: 'A 48-hour innovation sprint where visionaries converge to architect solutions powered by neural networks and AI. Push the boundaries of machine learning, build intelligent systems, and compete for groundbreaking prizes.',
    shortDescription: 'Build AI-powered solutions in 48 hours. Neural networks, deep learning, and intelligent systems.',
    organizer: { name: 'TechForge Labs', logo: '', id: 'org-001' },
    timeline: {
      registrationStart: '2026-03-01',
      registrationEnd: '2026-04-15',
      eventStart: '2026-04-25',
      eventEnd: '2026-04-27',
    },
    venue: 'Bengaluru International Centre & Online',
    prize: '₹5,00,000',
    maxParticipants: 500,
    registeredCount: 342,
    teamSize: { min: 2, max: 4 },
    tags: ['AI/ML', 'Deep Learning', 'Neural Networks', 'Innovation'],
    faqs: [
      { q: 'Who can participate?', a: 'Students, professionals, and teams from any background. Must be 18+ to register.' },
      { q: 'Is it free to participate?', a: 'Yes, participation is completely free. Travel and accommodation are not covered.' },
      { q: 'Can I participate solo?', a: 'Teams of 2-4 are required. Solo participants will be matched with others during team formation.' },
      { q: 'What should I bring?', a: 'Your laptop, charger, and passion for innovation. Food and beverages will be provided at the venue.' },
    ],
    imageUrl: '',
    featured: true,
    credentialEnabled: true,
    credentialTemplate: 'Classic',
    credentialConfig: {
      title: 'Certificate of Achievement',
      subtitle: 'This certificate is proudly presented to',
      description: 'For successfully completing Neural Nexus Hackathon 2026',
      signatoryName: 'Vikram Singh',
      signatoryRole: 'Program Director',
      logoUrl: '',
      sponsorLogoUrl: '',
    },
  },
  {
    id: 'evt-002',
    title: 'CloudStrike Summit',
    category: 'Conference',
    mode: 'Online',
    status: 'open',
    description: 'The premier cloud computing conference bringing together industry leaders, DevOps practitioners, and cloud architects. Featuring keynotes, workshops, and networking opportunities across multi-cloud ecosystems.',
    shortDescription: 'Premier cloud computing conference with industry leaders and hands-on workshops.',
    organizer: { name: 'CloudScale Foundation', logo: '', id: 'org-002' },
    timeline: {
      registrationStart: '2026-03-10',
      registrationEnd: '2026-04-20',
      eventStart: '2026-05-05',
      eventEnd: '2026-05-07',
    },
    venue: 'Virtual (Zoom + Gather.town)',
    prize: 'Certifications & Swag',
    maxParticipants: 2000,
    registeredCount: 1247,
    teamSize: null,
    tags: ['Cloud', 'DevOps', 'AWS', 'Azure', 'GCP'],
    faqs: [
      { q: 'Will sessions be recorded?', a: 'Yes, all sessions will be recorded and available for 30 days after the event.' },
      { q: 'Is there a participation fee?', a: 'Basic pass is free. Premium tracks with workshops cost ₹999.' },
    ],
    imageUrl: '',
    featured: true,
    credentialEnabled: true,
    credentialTemplate: 'Modern',
    credentialConfig: {
      title: 'Certificate of Participation',
      subtitle: 'This certificate is awarded to',
      description: 'For active participation in CloudStrike Summit',
      signatoryName: 'CloudScale Team',
      signatoryRole: 'Host',
      logoUrl: '',
      sponsorLogoUrl: '',
    },
  },
  {
    id: 'evt-003',
    title: 'CyberGuard CTF Challenge',
    category: 'Competition',
    mode: 'Online',
    status: 'open',
    description: 'Test your cybersecurity prowess in this Capture The Flag competition. Navigate through cryptography puzzles, reverse engineering challenges, and web exploitation scenarios to claim the title.',
    shortDescription: 'Capture The Flag cybersecurity competition. Cryptography, reversing, and web exploitation.',
    organizer: { name: 'SecureMinds Academy', logo: '', id: 'org-003' },
    timeline: {
      registrationStart: '2026-03-15',
      registrationEnd: '2026-04-10',
      eventStart: '2026-04-12',
      eventEnd: '2026-04-12',
    },
    venue: 'Online Platform',
    prize: '₹2,00,000',
    maxParticipants: 1000,
    registeredCount: 678,
    teamSize: { min: 1, max: 3 },
    tags: ['Cybersecurity', 'CTF', 'Ethical Hacking', 'Cryptography'],
    faqs: [
      { q: 'What skill level is required?', a: 'We have challenges for beginner, intermediate, and advanced levels.' },
      { q: 'What tools are allowed?', a: 'Any publicly available tools. Custom scripts are encouraged.' },
    ],
    imageUrl: '',
    featured: false,
  },
  {
    id: 'evt-004',
    title: 'DesignVerse Workshop Series',
    category: 'Workshop',
    mode: 'Offline',
    status: 'open',
    description: 'A 3-day intensive workshop series covering UI/UX design principles, Figma mastery, design systems, and user research methodologies. Perfect for aspiring and intermediate designers.',
    shortDescription: 'Intensive UI/UX workshop covering Figma, design systems, and user research.',
    organizer: { name: 'Pixel Collective', logo: '', id: 'org-004' },
    timeline: {
      registrationStart: '2026-03-01',
      registrationEnd: '2026-04-05',
      eventStart: '2026-04-10',
      eventEnd: '2026-04-12',
    },
    venue: 'Innovation Hub, Mumbai',
    prize: 'Certificates & Figma Pro Licenses',
    maxParticipants: 80,
    registeredCount: 72,
    teamSize: null,
    tags: ['UI/UX', 'Figma', 'Design Systems', 'User Research'],
    faqs: [
      { q: 'Do I need design experience?', a: 'Basic familiarity with design tools is helpful but not required.' },
      { q: 'Will materials be provided?', a: 'Yes, all worksheets, templates, and design kits will be shared digitally.' },
    ],
    imageUrl: '',
    featured: false,
  },
  {
    id: 'evt-005',
    title: 'GreenCode Carbon Hack',
    category: 'Hackathon',
    mode: 'Hybrid',
    status: 'upcoming',
    description: 'Build sustainable technology solutions that address climate change. Focus areas include carbon tracking, renewable energy optimization, sustainable supply chains, and environmental monitoring systems.',
    shortDescription: 'Sustainable tech hackathon tackling climate change through code.',
    organizer: { name: 'EcoTech Alliance', logo: '', id: 'org-005' },
    timeline: {
      registrationStart: '2026-04-01',
      registrationEnd: '2026-05-10',
      eventStart: '2026-05-20',
      eventEnd: '2026-05-22',
    },
    venue: 'Delhi NCR & Online',
    prize: '₹3,00,000 + Incubation',
    maxParticipants: 300,
    registeredCount: 45,
    teamSize: { min: 3, max: 5 },
    tags: ['Sustainability', 'CleanTech', 'Climate', 'Green IT'],
    faqs: [
      { q: 'What is the focus area?', a: 'Solutions addressing UN Sustainable Development Goals through technology.' },
    ],
    imageUrl: '',
    featured: true,
  },
  {
    id: 'evt-006',
    title: 'Blockchain Builders Bootcamp',
    category: 'Workshop',
    mode: 'Online',
    status: 'open',
    description: 'From zero to Web3 hero. Learn Solidity, smart contract development, DeFi protocols, and NFT ecosystems in this comprehensive 5-day bootcamp with hands-on labs and real project deployment.',
    shortDescription: 'Web3 bootcamp covering Solidity, smart contracts, DeFi, and NFTs.',
    organizer: { name: 'ChainCraft Studios', logo: '', id: 'org-006' },
    timeline: {
      registrationStart: '2026-03-20',
      registrationEnd: '2026-04-18',
      eventStart: '2026-04-22',
      eventEnd: '2026-04-26',
    },
    venue: 'Online (Discord + Live IDE)',
    prize: 'NFT Certificates + SDK Kits',
    maxParticipants: 200,
    registeredCount: 156,
    teamSize: null,
    tags: ['Blockchain', 'Web3', 'Solidity', 'DeFi', 'NFT'],
    faqs: [
      { q: 'Do I need blockchain knowledge?', a: 'Basic programming knowledge is required. Blockchain experience is not necessary.' },
    ],
    imageUrl: '',
    featured: false,
  },
  {
    id: 'evt-007',
    title: 'Data Odyssey Analytics Challenge',
    category: 'Competition',
    mode: 'Online',
    status: 'completed',
    description: 'A week-long data science competition where participants analyze real-world datasets, build predictive models, and present actionable insights. Featuring datasets from healthcare, finance, and social impact domains.',
    shortDescription: 'Data science competition with real-world datasets from healthcare and finance.',
    organizer: { name: 'DataWave Institute', logo: '', id: 'org-007' },
    timeline: {
      registrationStart: '2026-01-15',
      registrationEnd: '2026-02-10',
      eventStart: '2026-02-15',
      eventEnd: '2026-02-22',
    },
    venue: 'Online Platform',
    prize: '₹1,50,000',
    maxParticipants: 500,
    registeredCount: 423,
    teamSize: { min: 1, max: 2 },
    tags: ['Data Science', 'Machine Learning', 'Analytics', 'Python'],
    faqs: [],
    imageUrl: '',
    featured: false,
  },
  {
    id: 'evt-008',
    title: 'RoboArena',
    category: 'Competition',
    mode: 'Offline',
    status: 'open',
    description: 'India\'s largest robotics competition featuring autonomous navigation, drone challenges, and humanoid robot battles. Team up, build, and compete for glory in multiple tracks.',
    shortDescription: 'India\'s largest robotics competition with autonomous navigation and drone challenges.',
    organizer: { name: 'MechMinds Labs', logo: '', id: 'org-008' },
    timeline: {
      registrationStart: '2026-03-01',
      registrationEnd: '2026-04-20',
      eventStart: '2026-05-01',
      eventEnd: '2026-05-03',
    },
    venue: 'IIT Delhi Campus',
    prize: '₹8,00,000',
    maxParticipants: 150,
    registeredCount: 98,
    teamSize: { min: 3, max: 6 },
    tags: ['Robotics', 'IoT', 'Drones', 'Autonomous Systems'],
    faqs: [
      { q: 'Do we need to bring our own robots?', a: 'Yes, teams must build and bring their own robots. Component list will be shared after registration.' },
      { q: 'Is accommodation provided?', a: 'Limited hostel accommodation is available on campus. Register early to secure a spot.' },
    ],
    imageUrl: '',
    featured: true,
  },
];

export const sampleUsers = [
  {
    id: 'usr-001',
    name: 'Arjun Mehta',
    email: 'arjun@example.com',
    password: 'demo123',
    role: 'participant',
    avatar: '',
    institution: 'IIT Bombay',
    skills: ['Python', 'Machine Learning', 'React'],
    socials: { linkedin: '', github: '', instagram: '' },
    createdAt: '2026-01-15',
  },
  {
    id: 'usr-002',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    password: 'demo123',
    role: 'participant',
    avatar: '',
    institution: 'BITS Pilani',
    skills: ['UI/UX Design', 'Figma', 'JavaScript'],
    socials: { linkedin: '', github: '', instagram: '' },
    createdAt: '2026-02-01',
  },
];

export const sampleOrganizers = [
  {
    id: 'org-001',
    name: 'Vikram Singh',
    email: 'admin@techforge.com',
    password: 'demo123',
    role: 'organizer',
    avatar: '',
    organizationName: 'TechForge Labs',
    institutionName: 'Delhi Institute of Technology',
    hostType: 'hod',
    phoneNumber: '9876543210',
    state: 'Delhi',
    city: 'New Delhi',
    spocName: 'Vikram Singh',
    spocContact: '+91 98765 43210',
    spocEmail: 'vikram@techforge.com',
    hostOnboardingCompleted: true,
    createdAt: '2026-01-01',
  },
];

export const sampleRegistrations = [
  {
    id: 'reg-001',
    userId: 'usr-001',
    eventId: 'evt-001',
    participantType: 'developer',
    teamName: 'Neural Knights',
    teamSize: 3,
    teamLeadName: 'Arjun Mehta',
    members: ['Arjun Mehta', 'Ravi Kumar', 'Sneha Patel'],
    qrToken: 'QR-NX-001-USR001-2026',
    checkedIn: false,
    checkedInAt: null,
    createdAt: '2026-03-05',
  },
  {
    id: 'reg-002',
    userId: 'usr-001',
    eventId: 'evt-002',
    participantType: 'student',
    teamName: null,
    teamSize: null,
    teamLeadName: null,
    members: ['Arjun Mehta'],
    qrToken: 'QR-CS-002-USR001-2026',
    checkedIn: true,
    checkedInAt: '2026-05-05T09:30:00',
    createdAt: '2026-03-12',
  },
];

export const sampleCredentials = [
  {
    id: 'cred-001',
    userId: 'usr-001',
    eventId: 'evt-007',
    type: 'participation',
    issuedAt: '2026-02-25',
    credentialQR: 'CRED-DO-007-USR001-PART',
  },
];

export const eventCategories = ['Hackathon', 'Competition', 'Workshop', 'Conference', 'Bootcamp', 'Meetup'];
export const eventModes = ['Online', 'Offline', 'Hybrid'];
export const eventStatuses = ['open', 'upcoming', 'ongoing', 'completed'];

export const platformStats = {
  totalEvents: 250,
  totalParticipants: 50000,
  totalOrganizers: 120,
  totalCredentials: 35000,
  citiesReached: 45,
  successRate: 98.5,
};

export const testimonials = [
  {
    id: 1,
    name: 'Kavya Nair',
    role: 'Full Stack Developer',
    org: 'Google',
    text: 'Hunchmate transformed how I discover tech events. The QR-based entry was seamless, and I received my credential within hours of the event ending.',
    avatar: '',
  },
  {
    id: 2,
    name: 'Rahul Deshmukh',
    role: 'CTO',
    org: 'StartupGrid',
    text: 'As an organizer, managing 500+ registrations was effortless. The credential system saved us weeks of manual certificate generation.',
    avatar: '',
  },
  {
    id: 3,
    name: 'Ananya Gupta',
    role: 'CS Student',
    org: 'IIT Delhi',
    text: 'The platform made it incredibly easy to find relevant hackathons and keep track of all my achievements in one place.',
    avatar: '',
  },
];
